[package]
name = "makepad_7guis_counter"
version = "0.1.0"
edition = "2021"
description = "Makepad counter example"
license = "MIT OR Apache-2.0"

[dependencies]
makepad-widgets = { path = "../../widgets", version = "0.3.0" }
